[package]
name = "tcp_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
crossbeam-channel = "0.5.14"
serde = { version = "1.0.217", features = ["derive"] }

[[bin]]
name = "tcp_test"
path = "main.rs"
